/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * <h2><center>&copy; Copyright (c) 2021 STMicroelectronics.
 * All rights reserved.</center></h2>
 *
 * This software component is licensed by ST under BSD 3-Clause license,
 * the "License"; You may not use this file except in compliance with the
 * License. You may obtain a copy of the License at:
 *                        opensource.org/licenses/BSD-3-Clause
 *
 ******************************************************************************
 */

//this code will toggle PB13
#include <stdint.h>

#if !defined(__SOFT_FP__) && defined(__ARM_FP)
  #warning "FPU is not initialized, but the project is compiling for an FPU. Please initialize the FPU before use."
#endif


//function prototype for creating a human observable delay
void myDelay();

int main(void)
{
	//address of RCC_APB2ENR register
	uint32_t volatile *const pRccApb2Enr = (uint32_t*) 0x40021018;
	//address of GPIOB_CRH register
	uint32_t volatile *const pGpiobCrh   = (uint32_t*) 0x40010C04;
	//address of GPIOB_BSRR register
	uint32_t volatile *const pGpiobBsrr  = (uint32_t*) 0x40010C10;

	//enable the port b clock
	*pRccApb2Enr |= (1 << 3);

	//configure the GPIOB_CRH register
	//clear the CNF13[1:0] bits at bit position 23, 22
	*pGpiobCrh   &= ~(3 << 22);
	//set MODE13[1:0] to 10 at bit position 21, 20
	//set bit 21
	*pGpiobCrh   |= (1 << 21);
	//clear bit 20
	*pGpiobCrh   &= ~(1 << 20);


    /* Loop forever */
	while(1){

		//turn on the LED
		//clear BR13 at bit 29 and set BS13 at bit 13
		*pGpiobBsrr &= ~(1 << 29);
		*pGpiobBsrr |=  (1 << 13);

		//call the delay function
		myDelay();

		//turn off the LED
		//clear BS13 at bit 13 and set BR13 at bit 29
		*pGpiobBsrr &= ~(1 << 13);
		*pGpiobBsrr |=  (1 << 29);

		//call the delay function
		myDelay();
	}
}

//delay function definition
void myDelay(){

	for(uint32_t volatile i=0; i <= 200000; i++);
	//simply waste clock cycles by doing nothing
}
